channel: ~
timestamps: true
badges: true
timestamp_fmt: "%X"

# syntax "modifiers-char"
# modifiers:
# s : shift, c : ctrl, a : alt
# combine modifiers with a hyphen: c-a-2 is 'ctrl + alt + 2'

# examples:
# so: "s-a" would mean 'shift + a'
# a shorthand for the above is simply: 'A'
# f0 through f12 is supported. s-f2 is 'shift + f12'

keybinds:
  focus_status_view: "0"
  focus_messages_view: "1"
  focus_links_view: "2"
  focus_highlights_view: "3"
  quit: "q"
  toggle_timestamp: "t"
  toggle_badges: "b"

tabs:
  active:
    fg: "#FF0000"
    bg: ~
    effects: ~
  inactive:
    fg: "#FFFFFF"
    bg: ~
    effects: ~

tab_names:
  status: "Status"
  messages: "Messages"
  links: "Links"
  highlights: "Highlights"

colors:
  timestamp:
    fg: "#FF00FF"
    bg: ~
    effects: ~
  badges:
    admin:
      fg: "#FFFFFF"
      bg: ~
      effects: ~
    bits:
      fg: "#FFFFFF"
      bg: ~
      effects: ~
    broadcaster:
      fg: "#FF0000"
      bg: ~
      effects: bold
    global_mod:
      fg: "#FFFFFF"
      bg: ~
      effects: ~
    moderator:
      fg: "#FFFFFF"
      bg: ~
      effects: ~
    partner:
      fg: "#FFFFFF"
      bg: ~
      effects: ~
    premium:
      fg: "#FFFFFF"
      bg: ~
      effects: ~
    staff:
      fg: "#FFFFFF"
      bg: ~
      effects: ~
    subscriber:
      fg: "#FF0000"
      bg: ~
      effects: ~
    turbo:
      fg: "#FFFFFF"
      bg: ~
      effects: ~
    vip:
      fg: "#FFFFFF"
      bg: ~
      effects: ~

badge_names:
  admin: "admin"
  bits: "bits"
  broadcaster: "broadcaster"
  global_mod: "global_mod"
  moderator: "moderator"
  partner: "partner"
  premium: "premium"
  staff: "staff"
  subscriber: "subscriber"
  turbo: "turbo"
  vip: "vip"

highlights:
  mention:
    fg: "#FF0000"
    bg: ~
    effects: bold
  keywords:
    - name: Rust
      case_sensitive: false
      style:
        fg: "#F57C00"
        bg: ~
        effects: bold
    - name: Twitch
      case_sensitive: true
      style:
        fg: "#9146FF"
        bg: ~
        effects: bold
